# generated by DipDup 8.1.4

from __future__ import annotations

from typing import List

from pydantic import BaseModel, ConfigDict


class PrevOwnersInfoItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    address: str
    list: List[str]


class SvlsValue(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    VIN: str
    acceptRequest: bool
    brand: str
    climate: str
    color: str
    curr_owner_info: List[str]
    engine: str
    first_owner: bool
    fuel: str
    horsepower: str
    kilometers: str
    model: str
    owner: str
    prev_owners_info: List[PrevOwnersInfoItem]
    price: str
    request: str
    shift: str
    use: str
    vehicleSpecificType: str
    weight: str
    year: str
